### ISSUE TITLE
Support newline filenames in linux

### ISSUE THREAD

**Issue by jonniek** [jonniek/mpv-nextfile#8]
Linux version of the script currently runs the following command `ls -1vp` which results to output like
```
directory/
file1.mp4
file10.mp4
file11.mp4
```

This list is split by newline when parsing the files. However, newline is an allowed character in linux filenames so this will cause the script the break if such a file is encountered.

The fix to this issue is to list the files separated by forward slash while keeping the natural order of `ls -v`. Directories have to be handled correctly at parsing phase.
```
directory//file1.mp4/file10.mp4/file11.mp4
```
Expected parsed table(before applying extension filters)
```
{
  "directory/",
  "file1.mp4",
  "file10.mp4",
  "file11.mp4",
}
```

**Comment by Eisa01** [comment]
Hmm if I understand correctly, piping to sed should be sufficient to add forward slash. Also, it should increase the speed of listing files.

So if you just need to add a forward slash at the end of each line, this might help
`ls -vp | sed 's/$/\//'`

**Comment by jonniek** [comment]
> just need to add a forward slash at the end of each line

That's not quite sufficient, since a filename could include a newline like so:

```
directory/
file1.mp4
file
2.mp4
file3.mp4
```

Here `file\n2.mp4` would get split into two separate files which would fail to open.

I used something like `find . -File --format "%f/"` which splits them correctly with forward slash, but the issue is the `ls -v` natural order is lost.

Seems like `ls -b` might be useful. Running `ls -1vbp | tr '\n' '/'` results in:

```
directory//file1.mp4/file\n2.mp4/file3.mp4/
```

However, this seems to affect things like spaces as well which is bad. This website http://mywiki.wooledge.org/ParsingLs says ls shouldn't be used for parsing filenames.

Perhaps the only solution is to use find and sort the list in the lua script. I kind of dislike this solution though, since it relies on my sort implementation to be accurate and similar to the os. However, it would also make it easy to get files with `utils.readdir(dir, "files")`

**Comment by Eisa01** [comment]
I also dislike the solution of having to sort through lua :/
I thought that the previous sed command will work since I didnt see the issue of line break (\n) display in terminal output.

However, if having it all in one line should solve the issue, I think perl is the way to go:  
 `ls -vp | perl -pe 's/\n$/\//'`
This should result in an output like you mentioned and unlike tr, it should work with any weird character, spaces and others should work fine
`directory//file1.mp4/file\n2.mp4/file3.mp4/`

**Comment by jonniek** [comment]
Running that results in `directory//file1.mp4/file/2.mp4/file3.mp4/` for me.

If I go with the lua sorting then I think the same implementation as autoload http://www.davekoelle.com/files/alphanum.lua might be alright.

**Comment by Eisa01** [comment]
Ouch, strange that it is getting different results.
But since tr worked for you, maybe removing the new line with **tr** and adding the forward slash with perl or sed can be a solution?
`ls -vp | perl -pe 's/$/\//' | tr -d '\n'`

It is also listing the files correctly for me
`directory//file1.mp4/file\n2.mp4/file3.mp4/`

**Comment by jonniek** [comment]
Maybe your `file\n2.mp4` does not contain an actual newline? It should only display as `\n` if you list with `ls -b`. The fundamental problem is that you can't tell the difference from the newline in the filename and the newline formatted by the ls command. From piped programs point of view they are all the same.

**Comment by Eisa01** [comment]
@jonniek 
Had sometime to test the current way the listing is handled, I was surprised to see that new lines did not break the script, and executing the script simple cycled in the correct order.

I used Ubuntu 18.04, and had the following files:
`File 1.mp4, File 2.mp4, File 3.mp4, File 3 \n.mp4, File 4.mp4, File\n2.mp4`

I executed your script and it cycled them in the correct order, I checked the table contents your code is creating and it had no problems

Output of your table:
`{ [1] = File 1.mp4,[2] = File 2.mp4,[3] = File 3.mp4,[4] = File 3 \n.mp4,[5] = File 4.mp4,[6] = File\n2.mp4,}`

I am surprised, can you try cycling with the current code and see if the newline issue is actually there?

**Comment by jonniek** [comment]
Can you test renaming File 3 like so 
```
mv "File 3 \n.mp4" "File 3 
.mp4"
```
I suspect the \n is not an actual newline but literal character \ and n.

**Comment by Eisa01** [comment]
Finally I see the issue, and it sure is a tough nut to crack.. seems impossible to just fix it.
I tried the find command you used earlier, and for the new line file it actually listed it as `File 3?.mp4 ` which breaks the script as the file does not exist
> I used something like `find . -File --format "%f/"` which splits them correctly with forward slash, but the issue is the `ls -v` natural order is lost.

Having said that,
In ls there is -q , it might be helpful, it actually gave me the same output for the find command above, might be helpful to you since the find command did work for you?
`ls -qvp | perl -pe 's/\n$/\//'`

**Comment by jonniek** [comment]
This is the find version:  https://github.com/jonniek/mpv-nextfile/blob/ad118b9884cfa4bf8fb142a707d55ce562bbed17/nextfile.lua#L60

In the terminal it formats similar to `ls -q` but in the find version the newline information is not lost. I tried with adding q parameter to the current version of the `ls` and it fails for the same reason you mentioned. The find is able to play the file with a newline. I tested autoload and it seems like it also supports the file with a newline.

**Comment by Eisa01** [comment]
Attempted to do the sorting in various ways using bash but was not successful, so approached it differently to sort in lua.

Created a pull request leveraging your find command, and added a sort function to properly sort the files.
https://github.com/jonniek/mpv-nextfile/pull/11
